// Purpose: pulls Google Calendar events into sched_events for one calendar
// at a time (Phase 2, sync loop — Design Locks #1/#4). Handles incremental
// vs. full sync, category tagging, and the sched_sync_log audit trail.
// Inputs: a userId + calendarId + Category (resolved by the caller,
// sync-run/index.ts, from WORK_CAL_ID/PERSONAL_CAL_ID env vars) + a valid
// Google access token.
// Outputs: a SyncResult per call, and side effects in sched_events,
// sched_sync_state, sched_sync_log.
// Architecture note: syncTaskFieldsFromEvent (Design Lock #10, the
// Google -> step write-back half of the task link) is added to this file in
// Phase 4, once exporter.ts and the migration flow exist — Phase 2 has no
// task-linked events yet, so it isn't implemented here.

import { createClient } from 'npm:@supabase/supabase-js@2';
import { listEvents } from './calendar-client.ts';
import type { Category, EventSource, GoogleCalendarEvent, SchedEvent, SyncResult } from './types.ts';

function adminClient() {
  return createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );
}

const SEOUL_OFFSET = '+09:00'; // Design Lock #9 — timezone locked to Asia/Seoul everywhere

// Google auto-generates a recurring yearly event per Contact for birthdays/
// anniversaries; these aren't real schedule items, always carry one of these
// two Korean title patterns, and aren't individually manageable in Google
// Calendar anyway — excluded before they ever reach sched_events.
function isAutoGeneratedAnniversary(title: string | undefined): boolean {
  if (!title) return false;
  return title.includes('님의 생일') || title.includes('님의 기념일');
}

export function mapGoogleEventToSchedEvent(
  gEvent: GoogleCalendarEvent,
  userId: string,
  calendarId: string,
  category: Category,
): Omit<SchedEvent, 'id' | 'created_at' | 'updated_at'> {
  const allDay = !!gEvent.start.date && !gEvent.start.dateTime;
  // All-day events carry a bare 'YYYY-MM-DD' from Google with no timezone —
  // anchor it to Seoul midnight explicitly rather than letting the DB
  // session's timezone setting decide, per Design Lock #9.
  const startTs = allDay ? `${gEvent.start.date}T00:00:00${SEOUL_OFFSET}` : gEvent.start.dateTime!;
  const endTs = allDay ? `${gEvent.end.date}T00:00:00${SEOUL_OFFSET}` : gEvent.end.dateTime!;

  const source: EventSource =
    category === 'holiday' ? 'holiday'
    : gEvent.extendedProperties?.private?.source === 'schedule_app' ? 'app'
    : 'imported';

  // Google represents a recurring master's rule as one or more RFC 5545
  // lines (RRULE, plus optional EXRULE/EXDATE/RDATE) — only the RRULE line
  // itself maps to sched_events.rrule; the rest is out of scope until
  // rrule-engine.ts (Phase 6) needs finer-grained handling.
  const rruleLine = gEvent.recurrence?.find((line) => line.startsWith('RRULE:')) ?? null;

  return {
    user_id: userId,
    google_event_id: gEvent.id,
    calendar_id: calendarId,
    category,
    source,
    title: gEvent.summary ?? '(untitled)',
    description: gEvent.description ?? null,
    start_ts: startTs,
    end_ts: endTs,
    all_day: allDay,
    rrule: rruleLine ? rruleLine.slice('RRULE:'.length) : null,
    // Recurring-instance override linkage (matching a modified/cancelled
    // occurrence back to its local master row) needs a google_event_id ->
    // local id lookup that rrule-engine.ts owns — deferred to Phase 6, same
    // as the source prompt's own phase split. A modified instance still
    // gets its own sched_events row here (Google gives it a distinct id),
    // just not yet linked via recurrence_parent_id/override_of_event_id.
    recurrence_parent_id: null,
    override_of_event_id: null,
    override_start_ts: gEvent.originalStartTime?.dateTime ?? gEvent.originalStartTime?.date ?? null,
    // task_id is only ever set locally by exporter.ts's migration flow
    // (Phase 4) — never inferred from an imported Google event.
    task_id: null,
    last_synced_title: null,
    last_synced_date: null,
    color_override: null,
    extended_props: gEvent.extendedProperties?.private ?? null,
    synced_at: new Date().toISOString(),
  };
}

export async function upsertSchedEvents(
  rows: Array<Omit<SchedEvent, 'id' | 'created_at' | 'updated_at'>>,
): Promise<{ inserted: number; updated: number }> {
  if (rows.length === 0) return { inserted: 0, updated: 0 };
  const supabase = adminClient();

  // All rows in one call come from the same importCalendar invocation, so
  // they share one user_id/calendar_id. Fetch the existing google_event_ids
  // for just that (user, calendar) pair and diff locally — do NOT filter
  // this select by `.in('google_event_id', googleEventIds)`: on a first
  // full sync of a calendar with years of history, that embeds hundreds or
  // thousands of ids directly in the request URL and blows past
  // Postgres/Cloudflare's request-line size limit (this is what caused the
  // "http2 error: stream error" seen during Phase 2 testing). Scoping by
  // user_id + calendar_id alone gives the same answer with a small, bounded
  // request.
  const { data: existing, error: selectError } = await supabase
    .from('sched_events')
    .select('google_event_id')
    .eq('user_id', rows[0].user_id)
    .eq('calendar_id', rows[0].calendar_id!);
  if (selectError) throw new Error(`upsertSchedEvents read failed: ${selectError.message}`);
  const existingIds = new Set((existing ?? []).map((r) => r.google_event_id as string));

  const toInsert = rows.filter((r) => !existingIds.has(r.google_event_id!));
  const toUpdate = rows.filter((r) => existingIds.has(r.google_event_id!));

  // Batch inserts too — the same first-full-sync scenario can mean
  // thousands of new rows, and one giant insert risks the same kind of
  // request-size/time problem as the unbatched existence check above.
  const INSERT_BATCH_SIZE = 500;
  for (let i = 0; i < toInsert.length; i += INSERT_BATCH_SIZE) {
    const batch = toInsert.slice(i, i + INSERT_BATCH_SIZE);
    const { error } = await supabase.from('sched_events').insert(batch);
    if (error) throw new Error(`upsertSchedEvents insert failed: ${error.message}`);
  }

  // Existing rows: only touch the fields Google actually owns. task_id,
  // color_override, and last_synced_title/last_synced_date are local-only
  // state (a migrated task link, a display override, the J10 idempotency
  // guard) that Google's event resource has no concept of at all — a
  // blanket upsert of the full row would silently wipe them on every sync.
  for (const row of toUpdate) {
    const { error } = await supabase
      .from('sched_events')
      .update({
        category: row.category,
        source: row.source,
        title: row.title,
        description: row.description,
        start_ts: row.start_ts,
        end_ts: row.end_ts,
        all_day: row.all_day,
        rrule: row.rrule,
        recurrence_parent_id: row.recurrence_parent_id,
        override_of_event_id: row.override_of_event_id,
        override_start_ts: row.override_start_ts,
        extended_props: row.extended_props,
        synced_at: row.synced_at,
        updated_at: new Date().toISOString(),
      })
      .eq('user_id', row.user_id)
      .eq('google_event_id', row.google_event_id!)
      .eq('calendar_id', row.calendar_id!);
    if (error) throw new Error(`upsertSchedEvents update failed: ${error.message}`);
  }

  return { inserted: toInsert.length, updated: toUpdate.length };
}

// §Phase2 deviation from interface_contract.md: added a userId parameter.
// sched_sync_log.user_id is NOT NULL-worthy (every row should be traceable
// to a user) but SyncResult (the type the contract passes in) has no userId
// field — it's a display-oriented type the frontend also uses, where a
// per-user field would be redundant (the frontend already knows who's
// logged in). Threading userId as a separate argument avoids adding a field
// to SyncResult that only this one write path needs. Flagged in
// NOTES_phase2.md and interface_contract.md.
export async function logSyncRun(userId: string, result: SyncResult): Promise<void> {
  const supabase = adminClient();
  const { error } = await supabase.from('sched_sync_log').insert({
    user_id: userId,
    calendar_id: result.calendarId,
    ran_at: result.ranAt,
    events_added: result.eventsAdded,
    events_updated: result.eventsUpdated,
    events_deleted: result.eventsDeleted,
    error: result.error,
  });
  if (error) throw new Error(`logSyncRun failed: ${error.message}`);
}

export async function importCalendar(
  userId: string,
  calendarId: string,
  category: Category,
  accessToken: string,
): Promise<SyncResult> {
  const ranAt = new Date().toISOString();
  const supabase = adminClient();

  try {
    const { data: stateRow, error: stateError } = await supabase
      .from('sched_sync_state')
      .select('sync_token')
      .eq('user_id', userId)
      .eq('calendar_id', calendarId)
      .maybeSingle();
    if (stateError) throw new Error(`sched_sync_state read failed: ${stateError.message}`);

    let listResult = await listEvents(calendarId, accessToken, stateRow?.sync_token ?? undefined);
    if (listResult.fullSyncRequired) {
      // Stored syncToken expired/invalid (Google 410) — retry as a fresh
      // full sync with no syncToken at all.
      listResult = await listEvents(calendarId, accessToken);
    }

    // status='cancelled' entries are Google's way of reporting a deletion,
    // not a real event to store — split them out before mapping/upserting.
    // Auto-generated birthday/anniversary events are dropped the same way
    // (never stored, never counted) — see isAutoGeneratedAnniversary.
    const cancelled = listResult.events.filter((e) => e.status === 'cancelled');
    const active = listResult.events.filter(
      (e) => e.status !== 'cancelled' && !isAutoGeneratedAnniversary(e.summary),
    );

    const rows = active.map((e) => mapGoogleEventToSchedEvent(e, userId, calendarId, category));

    // Phase 6: link imported override instances to their local master row.
    // Google gives override instances a `recurringEventId` pointing at the
    // master's google_event_id. Look up the local master row and set
    // recurrence_parent_id + override_of_event_id so expandForRange can
    // apply overrides correctly.
    const overrideRows = active.filter((e) => !!e.recurringEventId);
    if (overrideRows.length > 0) {
      const masterGoogleIds = [...new Set(overrideRows.map((e) => e.recurringEventId!))];
      const { data: masterRows } = await supabase
        .from('sched_events')
        .select('id, google_event_id')
        .eq('user_id', userId)
        .eq('calendar_id', calendarId)
        .in('google_event_id', masterGoogleIds);
      const masterMap = new Map((masterRows ?? []).map((r) => [r.google_event_id, r.id]));
      for (let i = 0; i < active.length; i++) {
        const gEvent = active[i];
        if (gEvent.recurringEventId) {
          const localMasterId = masterMap.get(gEvent.recurringEventId);
          if (localMasterId) {
            rows[i].recurrence_parent_id = localMasterId;
            rows[i].override_of_event_id = localMasterId;
          }
        }
      }
    }

    const { inserted, updated } = await upsertSchedEvents(rows);

    let deleted = 0;
    const cancelledIds = cancelled.map((e) => e.id);
    if (cancelledIds.length > 0) {
      // Phase 2 note: this hard-deletes the local row on any cancellation,
      // which is correct for purely imported events (the only kind that
      // exist before Phase 4 adds push/un-push). Once source='app' pushed
      // events exist, a native Google-side deletion reaching here should
      // probably fall back to local-only (clear google_event_id/
      // calendar_id, keep the row) rather than deleting app-owned data —
      // revisit this branch when Phase 4 (Design Lock #14) ships.
      const { error: deleteError, count } = await supabase
        .from('sched_events')
        .delete({ count: 'exact' })
        .eq('user_id', userId)
        .eq('calendar_id', calendarId)
        .in('google_event_id', cancelledIds);
      if (deleteError) throw new Error(`sched_events delete failed: ${deleteError.message}`);
      deleted = count ?? 0;
    }

    await supabase.from('sched_sync_state').upsert(
      {
        user_id: userId,
        calendar_id: calendarId,
        sync_token: listResult.nextSyncToken,
        last_polled_at: ranAt,
      },
      { onConflict: 'user_id,calendar_id' },
    );

    const result: SyncResult = {
      calendarId,
      category,
      eventsAdded: inserted,
      eventsUpdated: updated,
      eventsDeleted: deleted,
      error: null,
      ranAt,
    };
    await logSyncRun(userId, result);
    return result;
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    const result: SyncResult = {
      calendarId,
      category,
      eventsAdded: 0,
      eventsUpdated: 0,
      eventsDeleted: 0,
      error: message,
      ranAt,
    };
    await logSyncRun(userId, result);
    return result;
  }
}
